version: "3.9"
services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    volumes:
      - events_mssql:/var/opt/mssql
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=7514895263a-B

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672

  api:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ~/.aspnet/https:/https:ro
    depends_on:
      - rabbitmq
      - db

  emailWorker:
    build: ./EmailWorker
    image: email-worker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBIT_HOSTNAME=rabbitmq
    restart: always
    depends_on:
      - rabbitmq
    entrypoint: ["./wait-for-it.sh", "rabbitmq:5672", "--", "./EmailWorker"]

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
      
volumes:
  events_mssql:
